---
# file: roles/galera/tasks/install.yml
- shell:
    rpm -aq | grep -i mariadb-libs-5.5.*x86_64 || true
  register: pkg
  when: ansible_os_family == 'RedHat'

- name: Removing old mariadb-libs package (RedHat family)
  package:
    name="{{ pkg.stdout }}"
    state=absent
  when: ansible_os_family == 'RedHat' and
        pkg.stdout != ''

- name: Installing MariaDB Galera packages
  package:
    name={{ item }}
    state=latest
  with_items:
    - "{{ galera_packages }}"

- name: ensure /var/run/mariadb exists
  file:
    path: /var/run/mariadb
    state: directory
    owner: mysql
    group: mysql
    mode: 0755
    
- name: ensure /var/log/mariadb exists
  file:
    path: /var/log/mariadb
    state: directory
    owner: mysql
    group: mysql
    mode: 0755