---
# file: roles/galera/tasks/pacemaker.yml
- name: Creating clustercheck SQL user (ready for Pacemaker)
  mysql_user:
    name={{ galera_clustercheck_user }}
    password={{ galera_clustercheck_password }}
    priv=*.*:USAGE
    state=present
  when: inventory_hostname == master

- name: Creating /etc/(sysconfig|default)/clustercheck file (ready for Pacemaker)
  template:
    src=etc/sysconfig/clustercheck.j2
    dest="{{ sysconfig_dir }}/clustercheck"

- name: Creating /usr/bin/clustercheck file (ready for Pacemaker)
  copy:
    src=usr/bin/clustercheck
    dest=/usr/bin/clustercheck
    mode=0755

- name: Creating /etc/xinet.d/galera-stream file (ready for Pacemaker)
  template:
    src=etc/xinetd.d/galera-stream.j2
    dest=/etc/xinetd.d/galera-stream
    mode=0600

- name: Enabling and starting xinetd service (ready for Pacemaker)
  service:
    name=xinetd
    state=started
    enabled=yes

- name: Stopping MariaDB service on slaves (ready for Pacemaker)
  service:
    name={{ mariadb_svc_name }}
    state=stopped
  when: inventory_hostname != master

- name: Stopping MariaDB service on master (ready for Pacemaker)
  service:
    name={{ mariadb_svc_name }}
    state=stopped
  when: inventory_hostname == master

- name: Deleting wsrep_cluster_address option (ready for Pacemaker)
  lineinfile:
    dest=/etc/{{ mariadb_config }}
    state=absent
    regexp='^wsrep_cluster_address='

- name: get galera members
  set_fact:
    wsrep_address: "gcomm://{{ groups[pacemaker_cluster_group]|join(',') }}"
    
- name: create galera in pacemaker
  pcs_resource: command=create resource_id=mysql type=ocf:heartbeat:galera master=true
  args:
    options:
      config: '/etc/my.cnf'
      check_user: 'clustercheck'
      check_passwd: 'mariadb'
      socket: '/var/lib/mysql/mysql.sock'
      pid: '/var/run/mariadb/mariadb.pid'
      log: '/var/log/mariadb/mariadb.log'
      binary: '/usr/bin/mysqld_safe'
      wsrep_cluster_address: "{{ wsrep_address }}"
    operations:
      - action: monitor
        options:
          interval: 60s
          timeout: 55s
      - action: start
        options:
          interval: 0s
          timeout: 330s
      - action: stop
        options:
          interval: 0s
          timeout: 120s
  run_once: true
